### ISSUE TITLE
not open

### ISSUE THREAD

**Issue by xxxshppee7xxx** [andrei-markeev/finnlingo#3]
i creat a facebook app 
and get an app id
and secret
put them in main.ts like that
appId: here the id number,
secret: here the secret
but it gived me a bug 
Your app is crashing. Here's the latest log:
Errors prevented startup:

While processing files with ts-decorators (for target os.windows.x86_32):
components/main/server/main.ts:9:29: ',' expected.

Your application has errors. Waiting for file change.

**Comment by andrei-markeev** [comment]
Hi,

I think the error description is quite self-explanatory. I assume that while you were adding the fb app credentials, you removed the comma accidentally.

**Comment by xxxshppee7xxx** [comment]
Meteor.startup(() => {

    ServiceConfiguration.configurations.upsert(
        { service: 'facebook' },
        {
            $set: {
                loginStyle: "redirect",
                appId: "1968736223170817",
                secret: "1118d00ec711f369f8f4d66704576d2d"
            }
        }
    );

    Meteor.publish('userData', function() {
        return Meteor.users.find({ _id: this.userId }, { fields: { study: 1 } });
    });

});
here is main.ts
and the error that has been given : 
Cannot find name 'ServiceConfiguration'
in the browser it said : 
Sign up or log in with Facebook
and when i click on it .. it's giving me this message : 

Warning
Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https://

**Comment by andrei-markeev** [comment]
hey, sorry I missed your reply
yes I can see you fixed the comma issue, great!

Again, the error is self explanatory: for FB integration to work, you need to have a site with SSL certificate installed. You can use http only with localhost.

Note: please never submit your credentials (fb app id and secret) to public sites such as here. Please re-generate the app secret as now it is compromised.
